server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anjali
    username: root
    password: Anjali@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
